<a href="https://colab.research.google.com/github/TeckHack76/Python_Worksheet/blob/main/Worksheet_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
#q1.1
import numpy as np
array1 =np.arange(5,26)
print(array1)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [21]:
#q1.2
import numpy as np
array2 = np.random.randint(10,50,size=(3,4))
print(array2)

[[27 31 31 24]
 [45 11 44 19]
 [17 40 42 28]]


In [24]:
#q2.1
print(array1.shape)

(21,)


In [ ]:
print(array1.size)

21


In [ ]:
print(array1.dtype)

int64


In [ ]:
#q2.2
print(array2.shape)
print(array2.size)
print(array2.dtype)

(3, 4)
12
int64


In [ ]:
#q3.1
import numpy as np
Array1 = np.array([2 ,4, 6, 8, 10])
Array2 = np.array([1, 3, 5, 7, 9])
print(Array1,Array2)

[ 2  4  6  8 10] [1 3 5 7 9]


In [ ]:
#q3.2
add = Array1 + Array2
print(add)
sub = Array1 - Array2
print(sub)
mul = Array1 * Array2
print(mul)
div = Array1 / Array2
print(div)

[ 3  7 11 15 19]
[1 1 1 1 1]
[ 2 12 30 56 90]
[2.         1.33333333 1.2        1.14285714 1.11111111]


In [12]:
#q4.1
import numpy as np
array = np.arange(1,10).reshape(3,3)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#q4.2
5*(array)

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
#q5
import numpy as np
array1 = np.arange(10,26).reshape(4,4)
print(array1)
print(array1[1])
print(array1[3])
array1[0]=0
print(array1)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[14 15 16 17]
[22 23 24 25]
[[ 0  0  0  0]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


In [16]:
#q6.1
import numpy as np
array = np.random.randint(20,40,size=[1,10])
print(array)

[[42 20 22 31 30 36 39 35 21 22]]


In [17]:
#q6.2
element = array[array>30]
print(element)

[42 31 36 39 35]


In [2]:
#q7.1
import numpy as np
array = np.random.randint(11,50,size=(1,12))
print(array)

[[25 44 18 34 31 12 15 39 29 20 17 46]]


In [3]:
#q7.2
print(array.reshape(3,4))

[[25 44 18 34]
 [31 12 15 39]
 [29 20 17 46]]


In [4]:
#q8.1
Matrix_A=np.array([[1,2],[3,4]])
Matrix_B=np.array([[5,6],[7,8]])
print(Matrix_A)
print(Matrix_B)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [5]:
#q8.2
np.dot(Matrix_A,Matrix_B)

array([[19, 22],
       [43, 50]])

In [8]:
transpose = Matrix_A.T
print(transpose)

[[1 3]
 [2 4]]


In [9]:
#q9.1
import numpy as np
A=np.random.randint(10,61,size=(1,15))
print(A)

[[32 51 57 57 14 40 41 60 11 10 60 45 29 13 58]]


In [14]:
#q9.2
print(np.mean(A))
print(np.median(A))
print(np.std(A))

38.53333333333333
41.0
18.525178061822302


In [20]:
#10
from numpy import linalg as LA
A=np.array([[2,1,3],[0,5,6],[7,8,9]])
print(A)
print(LA.det(A))
print(LA.inv(A))
print(LA.eig(A))

[[2 1 3]
 [0 5 6]
 [7 8 9]]
-68.99999999999996
[[ 0.04347826 -0.2173913   0.13043478]
 [-0.60869565  0.04347826  0.17391304]
 [ 0.50724638  0.13043478 -0.14492754]]
EigResult(eigenvalues=array([15.45215427,  2.40475147, -1.85690573]), eigenvectors=array([[-0.22453607, -0.55941438, -0.38300969],
       [-0.48513596,  0.7607706 , -0.60830181],
       [-0.84511931, -0.3290648 ,  0.69517803]]))
